In [ ]:
1) Different Data Structures Used in TensorFlow

TensorFlow, a popular open-source machine learning library, provides various data structures to facilitate the creation, 
manipulation, and training of machine learning models. Here are some key data structures:

Tensors: The core data structure of TensorFlow, analogous to multi-dimensional arrays or matrices in other libraries like NumPy.
         Tensors are immutable and can hold various types of data such as integers, floats, and strings.

Example: tf.constant([1, 2, 3])
Variables: Mutable data structures used to hold and update parameters in a machine learning model. Unlike tensors, variables 
           can be changed during training.

Example: tf.Variable([1.0, 2.0, 3.0])
Datasets: Used for input pipelines to efficiently load and preprocess data. The tf.data.Dataset API provides tools to create 
          and manipulate datasets.

Example: tf.data.Dataset.from_tensor_slices([1, 2, 3])
Placeholders: In TensorFlow 1.x, placeholders were used to feed data into the model during runtime. However, they are 
              deprecated in TensorFlow 2.x, where the tf.function and eager execution are preferred.

Example: tf.placeholder(tf.float32, shape=[None, 2]) (TensorFlow 1.x)
Queues: Used in TensorFlow 1.x for managing asynchronous data pipelines. Deprecated in TensorFlow 2.x in favor of the tf.data 
        API.

In [ ]:
2)
TensorFlow Constants: These are immutable tensors whose values cannot be changed once assigned. Constants are used for values 
    that remain fixed during the computation.

TensorFlow Variables: These are mutable tensors whose values can be changed during the computation. Variables are primarily 
    used to hold and update parameters in machine learning models.

In [1]:
import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Add the matrices
matrix_sum = tf.add(matrix1, matrix2)
print("Matrix Addition:\n", matrix_sum)


Matrix Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [ ]:
PART-2

In [2]:
import tensorflow as tf

# Set dimensions
x = 3

A = tf.random.normal(shape=(x, x))
print("Matrix A:\n", A)


Matrix A:
 tf.Tensor(
[[ 4.8770827e-01 -1.4136240e+00  1.6714063e+00]
 [ 1.1824137e-01  7.9592311e-01 -1.8063000e+00]
 [ 1.5517495e-03  6.4159763e-01  7.7831095e-01]], shape=(3, 3), dtype=float32)


In [3]:
# Create matrix B with truncated normal values
B = tf.random.truncated_normal(shape=(x, x))
print("Matrix B:\n", B)

Matrix B:
 tf.Tensor(
[[-1.2909336e+00 -1.4959207e+00  1.4858916e+00]
 [ 1.2977252e+00 -1.4775197e-01  3.9496846e-02]
 [-8.6138934e-01  1.4460276e+00  7.1383105e-04]], shape=(3, 3), dtype=float32)


In [4]:
# Create matrix C with normal distribution, mean 0, stddev 0.1
C = tf.random.normal(shape=(2, 2), mean=0, stddev=0.1)
print("Matrix C:\n", C)


Matrix C:
 tf.Tensor(
[[-0.14856967  0.17565279]
 [ 0.17448376  0.05214239]], shape=(2, 2), dtype=float32)


In [7]:
# Perform matrix addition to get D
D = tf.add(A, B)
print("Matrix D (A + B):\n", D)

Matrix D (A + B):
 tf.Tensor(
[[-0.80322534 -2.9095447   3.1572978 ]
 [ 1.4159665   0.6481711  -1.7668031 ]
 [-0.8598376   2.0876253   0.7790248 ]], shape=(3, 3), dtype=float32)


In [9]:
C = tf.random.normal(shape=(2, x), mean=0, stddev=0.1)
print("Matrix C:\n", C)

# Perform matrix multiplication to get E
E = tf.matmul(C, D)
print("Matrix E (C * D):\n", E)

Matrix C:
 tf.Tensor(
[[-0.13691895  0.10624775  0.02410238]
 [ 0.12320682  0.05607012 -0.00933483]], shape=(2, 3), dtype=float32)
Matrix E (C * D):
 tf.Tensor(
[[ 0.23969589  0.51755524 -0.6012364 ]
 [-0.01154299 -0.34162033  0.2826637 ]], shape=(2, 3), dtype=float32)


In [ ]:
TASK-3

In [10]:
import tensorflow as tf

# 1) Create matrix F with random uniform values
F = tf.random.uniform(shape=(2, 2))
print("Matrix F:\n", F.numpy())

# 2) Calculate the transpose of F
G = tf.transpose(F)
print("Matrix G (Transpose of F):\n", G.numpy())

# 3) Calculate the element-wise exponential of F
H = tf.exp(F)
print("Matrix H (Element-wise Exponential of F):\n", H.numpy())

# 4) Concatenate F and G horizontally to create I
I = tf.concat([F, G], axis=1)
print("Matrix I (Concatenation of F and G horizontally):\n", I.numpy())

# 5) Concatenate F and H vertically to create J
J = tf.concat([F, H], axis=0)
print("Matrix J (Concatenation of F and H vertically):\n", J.numpy())


Matrix F:
 [[0.6795862  0.48375654]
 [0.06231523 0.38037205]]
Matrix G (Transpose of F):
 [[0.6795862  0.06231523]
 [0.48375654 0.38037205]]
Matrix H (Element-wise Exponential of F):
 [[1.9730611 1.6221566]
 [1.0642978 1.4628288]]
Matrix I (Concatenation of F and G horizontally):
 [[0.6795862  0.48375654 0.6795862  0.06231523]
 [0.06231523 0.38037205 0.48375654 0.38037205]]
Matrix J (Concatenation of F and H vertically):
 [[0.6795862  0.48375654]
 [0.06231523 0.38037205]
 [1.9730611  1.6221566 ]
 [1.0642978  1.4628288 ]]
